# For uv @ https://docs.astral.sh/uv/
[project]
name = "pybooktools"
version = "0.1.0"
description = "Tools I use for writing Python books."
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "astor>=0.8.1",
    "icecream>=2.1.3",
    "rich>=13.9.4",
]

[project.scripts]
c = "pybooktools.reminder:main"
ocl = "pybooktools.ocl.produce_ocled_example:main"
bookup = "pybooktools.update_markdown_code_listings:main"
slug = "pybooktools.slug_line:main"
chapnum = "pybooktools.renumber_chapters:main"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 80

[tool.pytest.ini_options]
pythonpath = ["src/pybooktools"]
