[project]
name = "pybooktools"
version = "0.1.0"
description = "Tools I use for writing Python books."
authors = [{ name = "Bruce Eckel", email = "MindviewInc@gmail.com" }]
dependencies = [
    "rich>=13.9.4",
    "mypy>=1.11.1",
    "libcst>=1.5.1",
    "icecream>=2.1.3",
    "pydantic>=2.10.3",
    "dill>=0.3.9",
]
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
selfgen = "pybooktools.self_gen.generate_ocl_example:main"
genocl = "pybooktools.ocl.generate_ocl:main"
z = "pybooktools.reminder:main"
slug = "pybooktools.slug_line:main"
chapz = "pybooktools.renumber_chapters:main"
checkpy = "pybooktools.check_example_output:main"
pyup = "pybooktools.update_example_output:main"
xv = "pybooktools.remove_validation_dir:main"
exnum = "pybooktools.output_validator.s1_number_output_strings:main"
etrack = "pybooktools.output_validator.s2_add_output_tracking:main"
exup = "pybooktools.output_validator.s3_incorporate_tracked_output:main"
exval = "pybooktools.output_validator.s3_validate_tracked_output:main"
exadj = "pybooktools.output_validator.s4_adjust_indentation:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.1.1",
    "black>=24.4.2",
    "pytest-mock>=3.14.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pybooktools"]

[tool.black]
line-length = 80

[tool.pytest.ini_options]
#pythonpath = ["src/pybooktools"]
norecursedirs = ["graveyard"]
