# For uv @ https://docs.astral.sh/uv/
[project]
name = "pybooktools"
version = "0.1.1"
description = "Tools I use for writing Python books."
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "icecream>=2.1.3",
    "pytest>=8.3.4",
    "rich>=13.9.4",
    "typer>=0.15.1",
]

[project.scripts]
px = "pybooktools.tls.update_example_output:main"
cr = "pybooktools.reminder:main"
bookup = "pybooktools.update_markdown_python_examples:app"
slug = "pybooktools.slug_line:app"
chapnum = "pybooktools.renumber_chapters:app"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

#[tool.black]
#line-length = 80

[tool.pytest.ini_options]
pythonpath = ["src/pybooktools"]

[tool.hatch.build.targets.wheel]
packages = ["src/pybooktools"]
